config/routes.rb
Rails.application.routes.draw do
  resources :examples
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions'
  }

  devise_scope :user do
    namespace :users do
      get 'dashboards/index', as: :root
    end
  end

  devise_scope :admin do
    namespace :admins do
      get 'dashboards/index', as: :root
      resources :users, only: [:index, :destroy, :edit, :update]
      resources :questions
    end
  end

  root to: 'users/dashboards#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers, dependent: :destroy
    accepts_nested_attributes_for :answers
    validates :content, presence: true

    enum category: {Art: 0, Geography: 1, English: 2, Literacy: 3, Music: 4, Science: 5}
    enum level: {Easy: 0, Normal: 1, Hard: 2}
end

app/controllers/admins/questions_controller.rb
class Admins::QuestionsController < Admins::AdminsController
    before_action :set_question, only: [:edit, :show, :destroy, :update]

    def index
        @search = Question.ransack(params[:q])
        @questions = @search.result.page(params[:page]).per(10)
    end

    def edit
    end

    def new
        @question = Question.new
        (1..4).each { @question.answers.build }
    end

    def update
        respond_to do |format|
            if @question.update(question_params)
                format.html { redirect_to admins_questions_path(@question), notice: 'Question was successfully updated.' }
            else
                flash[:error] = "An error has occurred while"
                format.html { render :edit, error: 'Error updating question'}
            end
        end
    end

    def create
        @question = Question.new(question_params)
        respond_to do |format|
            if @question.save
                format.html { redirect_to new_admins_question_path, notice: 'Question was successfully created'}
            else
                flash[:error] = @question.errors.full_messages.first.gsub!(/[^a-zA-Z ]/,'')
                format.html { redirect_to new_admins_question_path }
            end
        end
    end

    def destroy
        if @question.destroy
            flash[:success] = "Question was successfully destroyed"
        else
            flash[:danger] = "Question was not destroyed"
        end
        redirect_to  admins_questions_path
    end
    
    private
        def set_question
            @question = Question.find(params[:id])
        end

        def question_params
            params.require(:question).permit(:content, :category, :type, :level, answers_attributes: [:content, :correct])
        end
end

app/helpers/admins/questions_helper.rb
module Admins::QuestionsHelper
end

app/views/admins/questions/_form.html.erb
<h2> <%= resource_name.to_s.humanize %></h2>

<%= form_for(resource, as: resource_name, url: url, html: { method: method }) do |f| %>

  <div class="field row">
    <div class="col-1">
      <%= f.label :content, class: 'form-label' %>
    </div>
    <div class="col-11">
      <%= f.text_field :content, autofocus: true, autocomplete: "content", class: 'col-5 form-control', required: true %>
    </div>
  </div>

  <div class="field row mt-4 d-flex justify-content-start mb-4 align-items-center">
    <div class="col-1">
      <%= f.label :category, class: 'form-label' %>
    </div>
    <div class="col-5">
      <%= f.select :category, Question.categories.keys, {include_blank: true}, class: 'form-select', required: true %>
    </div>

    <div class="col-1">
      <%= f.label :level %>
    </div>
    <div class="col-5">
      <%= f.select :level, Question.levels.keys, {include_blank: true}, class: 'form-select', required: true %>
    </div>
  </div>

  <div class="field">
    <h5>Answers</h5>
    <div class="row mt-4 d-flex justify-content-start align-items-center">
      <%= f.fields_for :answers do |ff| %>
        <div class="col-5">
          <%= ff.text_field :content, class: 'form-control col-5 mb-4', required: true %>
        </div>
        <div class="col-1">
          <%= ff.check_box :correct, class: 'col-1 form-check-input mb-4' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="action">
    <%= f.submit method=="POST"? "Create" : "Update", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admins/questions/edit.html.erb
<%= render 'form', resource: @question, resource_name: 'question', method: "PUT", url: admins_question_path(@question)  %>

app/views/admins/questions/index.html.erb
<h2> <%= Question %></h2>
<%= search_form_for @search, url: admins_questions_path, class: "form-inline" do |f| %>
	<div class="form-group">
        <div class="row">
            <div class="col-1">
                <%= f.label :content_cont, 'Content:' %>
            </div>
            <div class="col-11">
                <%= f.text_field :content_cont, class: "form-control" %><br>
            </div>
        </div>
        <div class="row d-flex justify-content-start mb-4 align-items-center">
            <div class="col-1">
                <%= f.label :category_eq, 'Category:' %>
            </div>
            <div class="col-5">
                <%= f.select :category_eq, options_from_collection_for_select(Question.categories, "second", "first", @search.category_eq), {include_blank: true}, {class: 'form-select'} %>
            </div>
            <div class="col-1">
                <%= f.label :level_eq, 'Level:' %>
            </div>
            <div class="col-5">
                <%= f.select :level_eq, options_from_collection_for_select(Question.levels, "second", "first", @search.level_eq), {include_blank: true}, {class: 'form-select'} %>
            </div>
        </div>
    </div>
    <%= f.submit 'Search', class: "btn btn-primary mb-4" %>
<% end %>
<table class="table">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Content</th>
        <th scope="col">Category</th>
        <th scope="col">Level</th>
        <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @questions.each.with_index(1) do |question, index| %>
            <tr>
                <th scope="col"><%= index %></th>
                <td class="col-md-8"><%= question.content %></td>
                <td class="col-md-1"><%= question.category %></td>
                <td class="text-<%= question.level == "Easy"? "primary" : (question.level == 'Normal' ? "success" : "danger") %>"><%= question.level %></td>
                <td class=""><%= link_to "Edit", edit_admins_question_path(question), class: 'btn btn-primary' %>
                <%= link_to "Destroy", admins_question_path(question), method: :delete , data: {:confirm => "You sure?" }, class: 'btn btn-danger' %></td>
            </tr>
        <% end %>
        <%= paginate @questions, theme: 'twitter-bootstrap-4' %>
    </tbody>
</table>

app/views/admins/questions/new.html.erb
<%= render 'form', resource: @question, resource_name: 'question', method: "POST", url: admins_questions_path  %>