config/routes.rb
Rails.application.routes.draw do
  resources :examples
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions'
  }

  devise_scope :user do
    namespace :users do
      get 'dashboards/index', as: :root
    end
  end

  devise_scope :admin do
    namespace :admins do
      get 'dashboards/index', as: :root
      resources :users, only: [:index, :destroy, :edit, :update]
      resources :questions
    end
  end

  root to: 'users/dashboards#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::AdminsController
    before_action :set_user, only: [:update, :edit, :destroy]
    def index
        @users = User.all.page(params[:page]).per(6)
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:success] = "User successfully updated"
        else
            flash[:danger] = "User not updated"
        end
        redirect_to edit_admins_user_path(@user)
    end

    def destroy
        if @user.destroy
            flash[:notice] = "User has been deleted"
        else
            flash[:notice] = "Delete user not allowed"
        end
        redirect_to admins_users_path
    end

    private
        def set_user
            @user = User.find(params[:id])
        end

        def user_params
            params.require(:user).permit(:email, :password, :password_confirmation)
        end
end

app/controllers/users/dashboards_controller.rb
class Users::DashboardsController < Users::UsersController
  def index
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  include Accessible
  skip_before_action :check_resource, except: [:new, :create]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  include Accessible
  skip_before_action :check_resource, only: :destroy
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
    before_action :authenticate_user!
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users/dashboards_helper.rb
module Users::DashboardsHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/users/_form.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= form_for(resource, as: resource_name, url: admins_user_path(resource), html: { method: :put }) do |f| %>
  <%= render "users/shared/error_messages", resource: resource %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>
  <div class="action">
    <%= f.submit "Update", class: 'btn btn-primary' %>
    <%= link_to "Destroy", admins_user_path(resource), method: :delete , data: {:confirm => "You sure?" }, class: 'btn btn-danger' %>
  </div>
<% end %>

<%= link_to 'Back', :back %>

app/views/admins/users/edit.html.erb
<%= render 'form', resource: @user, resource_name: 'user' %>

app/views/admins/users/index.html.erb
<table class="table">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Email</th>
        <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each.with_index(1) do |user, index| %>
            <tr>
                <th scope="col"><%= index %></th>
                <td><%= user.email %></td>
                <td class=""><%= link_to "Edit", edit_admins_user_path(user), class: 'btn btn-primary' %>
                <%= link_to "Destroy", admins_user_path(user), method: :delete , data: {:confirm => "You sure?" }, class: 'btn btn-danger' %></td>
            </tr>
        <% end %>
        <%= paginate @users, theme: 'twitter-bootstrap-4' %>
    </tbody>
</table>